// FIX: Replaced component code with the translations object to fix import errors.
export const translations = {
  en: {
    // MainMenu
    game_setup: 'Game Setup',
    player_1_deck: 'Player 1 Deck',
    player_2_cpu_deck: 'Player 2 / CPU Deck',
    choose_starting_player: 'Choose Starting Player',
    player_1_start: 'Player 1',
    player_2_start: 'Player 2',
    start_vs_cpu: 'Start vs CPU',
    start_solitaire: 'Start PvP (Solitaire)',
    deck_builder_menu: 'Deck Builder',
    fan_disclaimer: 'This is a fan-made work created based on the "Daiso Publishing Trading Card Game Product Copyright Usage Guidelines for Derivative Works and Fan Activities". The images are quoted from the official website. Not for commercial use.',

    // DeckBuilder
    new_deck_default_name: 'New Deck',
    deck_name_required: 'Deck name is required.',
    deck_saved_alert: 'saved!',
    deck_not_saved_alert: 'This deck has not been saved yet.',
    delete_deck_confirm: 'Are you sure you want to delete',
    search_by_name: 'Search by name...',
    filter_all_colors: 'All Colors',
    filter_all_types: 'All Types',
    card_type_monster: 'Monster',
    card_type_spell: 'Spell',
    card_type_attachment: 'Attachment',
    card_type_magic: 'Magic',
    deck_name_placeholder: 'Deck Name',
    load_deck_button: 'Load Deck',
    new_deck_button: 'New',
    save_deck_button: 'Save',
    delete_deck_button: 'Delete',
    export_deck_button: 'Export',
    import_deck_button: 'Import',
    deck_imported_successfully: 'Deck "{deckName}" imported successfully!',
    deck_import_failed: 'Failed to import deck. The file may be invalid.',
    view_deck_button: 'View Deck',
    view_collection_button: 'View Collection',
    main_deck_header: 'Main Deck',
    magic_deck_header: 'Magic Deck',
    click_card_to_view: 'Click a card to view details.',
    deckbuilder_help_title: 'Deck Builder Help',
    deckbuilder_help_add_title: 'Add Card',
    deckbuilder_help_add_desc_pc: 'Click a card from the collection on the left to add it to your deck.',
    deckbuilder_help_add_desc_sp: 'Tap a card in the main list to add it to your deck.',
    deckbuilder_help_remove_title: 'Remove Card',
    deckbuilder_help_remove_desc_pc: 'Click a card from your deck list on the right to remove it.',
    deckbuilder_help_remove_desc_sp: "Tap the 'View Deck' bar at the bottom, then tap a card in the list to remove it.",
    deckbuilder_help_details_title_pc: 'View Details',
    deckbuilder_help_details_desc_pc: 'Hover over any card to see its full details on the far right.',
    deckbuilder_help_details_title_sp: 'View Details',
    deckbuilder_help_details_desc_sp: 'Press and hold on any card to see its full details.',
    deckbuilder_help_save_title: 'Save Deck',
    deckbuilder_help_save_desc: 'Enter a deck name. The "Save" button will be enabled when your deck meets the size requirements (20 Main, 10 Magic).',
    deckbuilder_help_load_title: 'Load Deck',
    deckbuilder_help_load_desc: 'Select a previously saved deck from the "Load Deck" dropdown to edit it.',
    deckbuilder_help_actions_title: 'Other Actions',
    deckbuilder_help_actions_desc: '"New" clears the current deck. "Delete" removes the loaded saved deck. "Import/Export" allows you to share deck files.',
    close_button: 'Close',

    // App/General
    header_title: '千怪戦戯',
    language_toggle: '日本語',
    back_to_menu: 'Back to Menu',
    end_game: 'End Game',

    // GameBoard
    magic_zone: "Magic Zone",
    empty: 'Empty',
    click_to_see_details: 'Click a card or monster to see details.',
    card_cost: 'Cost',
    player_x: '{player}',
    thinking: 'CPU is thinking...',
    upkeep_phase: "{player}'s Upkeep Phase",
    draw_phase: "{player}'s Draw Phase",
    set_phase: "{player}'s Set Phase",
    end_phase: "{player}'s End Phase",
    main_phase_first_turn_player: "Main Phase. You cannot attack this turn.",
    attachment_selected: "Select a monster to attach this to.",
    spell_selected: "Select a target for this spell.",
    card_selected_lane: "Select a lane to play this monster.",
    monster_selected_tapped: "This monster is tapped and cannot attack.",
    monster_selected_wimpy: "This monster cannot attack players directly.",
    monster_selected_attack: "Select an opponent's monster to attack.",
    main_phase_generic: "{player}'s Main Phase.",
    guidance_discard: "{player}, select a card to discard.",
    guidance_select_target: "Select a target for the effect.",
    guidance_choose_effect_awaken: "{player}, use Awakened Magic to return {cardName} to hand?",
    guidance_choose_effect: "{player}, use {cardName}'s effect?",
    show_details_button: 'Details',
    yes: 'Yes',
    no: 'No',
    attack_player: 'Attack Player',
    end_main_phase: 'End Main Phase',
    new_game: 'New Game',
    deck: 'Deck',
    magic: 'Magic',

    // Colors
    color_red: 'Red',
    color_green: 'Green',
    color_blue: 'Blue',
    color_colorless: 'Colorless',
    color_red_awakened: 'Red (Awakened)',
    color_green_awakened: 'Green (Awakened)',
    color_blue_awakened: 'Blue (Awakened)',
    color_colorless_flipped: 'Flipped',

    // Deck Names
    deck_name_blue: 'Blue Starter',
    deck_name_green: 'Green Starter',
    deck_name_red: 'Red Starter',
  },
  ja: {
    // MainMenu
    game_setup: 'ゲーム設定',
    player_1_deck: 'プレイヤー1のデッキ',
    player_2_cpu_deck: 'プレイヤー2 / CPUのデッキ',
    choose_starting_player: '先攻プレイヤー選択',
    player_1_start: 'プレイヤー1',
    player_2_start: 'プレイヤー2',
    start_vs_cpu: 'CPUと対戦',
    start_solitaire: '対人戦 (ソロプレイ)',
    deck_builder_menu: 'デッキ構築',
    fan_disclaimer: '「大創出版「トレーディングカードゲーム商品の著作物利用に関する二次創作、ファン活動ガイドライン」に基づいて制作された二次創作作品です。画像は公式サイトから引用したものを用いています。商用利用はできません。」',

    // DeckBuilder
    new_deck_default_name: '新しいデッキ',
    deck_name_required: 'デッキ名を入力してください。',
    deck_saved_alert: 'を保存しました！',
    deck_not_saved_alert: 'このデッキはまだ保存されていません。',
    delete_deck_confirm: '本当に「{name}」を削除しますか？',
    search_by_name: 'カード名で検索...',
    filter_all_colors: 'すべての色',
    filter_all_types: 'すべてのタイプ',
    card_type_monster: '怪魔',
    card_type_spell: '計略',
    card_type_attachment: '付与',
    card_type_magic: '魔力',
    deck_name_placeholder: 'デッキ名',
    load_deck_button: 'デッキ読込',
    new_deck_button: '新規',
    save_deck_button: '保存',
    delete_deck_button: '削除',
    export_deck_button: 'エクスポート',
    import_deck_button: 'インポート',
    deck_imported_successfully: 'デッキ「{deckName}」を正常にインポートしました！',
    deck_import_failed: 'デッキのインポートに失敗しました。ファイルが不正な可能性があります。',
    view_deck_button: 'デッキ表示',
    view_collection_button: 'カード一覧表示',
    main_deck_header: 'メインデッキ',
    magic_deck_header: '魔力デッキ',
    click_card_to_view: 'カードをクリックして詳細表示',
    deckbuilder_help_title: 'デッキ構築ヘルプ',
    deckbuilder_help_add_title: 'カードの追加',
    deckbuilder_help_add_desc_pc: '左側のカード一覧からカードをクリックすると、デッキに追加されます。',
    deckbuilder_help_add_desc_sp: 'メインのカード一覧でカードをタップするとデッキに追加されます。',
    deckbuilder_help_remove_title: 'カードの削除',
    deckbuilder_help_remove_desc_pc: '右側のデッキリストからカードをクリックすると、デッキから削除されます。',
    deckbuilder_help_remove_desc_sp: '画面下部の「デッキ表示」バーをタップし、表示されたリスト内のカードをタップすると削除できます。',
    deckbuilder_help_details_title_pc: '詳細表示',
    deckbuilder_help_details_desc_pc: 'カードにカーソルを合わせると、右側に詳細が表示されます。',
    deckbuilder_help_details_title_sp: '詳細表示',
    deckbuilder_help_details_desc_sp: 'カードを長押しすると、詳細が表示されます。',
    deckbuilder_help_save_title: 'デッキの保存',
    deckbuilder_help_save_desc: 'デッキ名を入力してください。デッキの枚数条件（メイン20枚、魔力10枚）を満たすと「保存」ボタンが有効になります。',
    deckbuilder_help_load_title: 'デッキの読込',
    deckbuilder_help_load_desc: '「デッキ読込」から保存済みのデッキを選択すると、そのデッキを編集できます。',
    deckbuilder_help_actions_title: 'その他の操作',
    deckbuilder_help_actions_desc: '「新規」で現在のデッキをクリアします。「削除」で読み込み中の保存済みデッキを削除します。「インポート/エクスポート」でデッキファイルを共有できます。',
    close_button: '閉じる',
    
    // App/General
    header_title: '千怪戦戯',
    language_toggle: 'English',
    back_to_menu: 'メニューに戻る',
    end_game: 'ゲーム終了',
    
    // GameBoard
    magic_zone: '魔力ゾーン',
    empty: 'なし',
    click_to_see_details: 'カードや怪魔をクリックして詳細を確認。',
    card_cost: 'コスト',
    player_x: '{player}',
    thinking: 'CPU思考中...',
    upkeep_phase: '{player}のアップキープフェイズ',
    draw_phase: '{player}のドローフェイズ',
    set_phase: '{player}のセットフェイズ',
    end_phase: '{player}のエンドフェイズ',
    main_phase_first_turn_player: "メインフェイズ。このターンは攻撃できません。",
    attachment_selected: "付与する対象の怪魔を選択してください。",
    spell_selected: "計略の対象を選択してください。",
    card_selected_lane: "この怪魔を配置するレーンを選択してください。",
    monster_selected_tapped: "この怪魔はダウンしており攻撃できません。",
    monster_selected_wimpy: "この怪魔はプレイヤーに直接攻撃できません。",
    monster_selected_attack: "攻撃する相手の怪魔を選択してください。",
    main_phase_generic: "{player}のメインフェイズ。",
    guidance_discard: "{player}、捨てるカードを選択してください。",
    guidance_select_target: "効果の対象を選択してください。",
    guidance_choose_effect_awaken: "{player}、覚醒魔力を使って{cardName}を手札に戻しますか？",
    guidance_choose_effect: "{player}、{cardName}の効果を使いますか？",
    show_details_button: '詳細',
    yes: 'はい',
    no: 'いいえ',
    attack_player: 'プレイヤーへ攻撃',
    end_main_phase: 'メイン終了',
    new_game: '新しいゲーム',
    deck: '山札',
    magic: '魔力',

    // Colors
    color_red: '赤',
    color_green: '緑',
    color_blue: '青',
    color_colorless: '無',
    color_red_awakened: '赤(覚醒)',
    color_green_awakened: '緑(覚醒)',
    color_blue_awakened: '青(覚醒)',
    color_colorless_flipped: '裏向き',

    // Deck Names
    deck_name_blue: '青スターター',
    deck_name_green: '緑スターター',
    deck_name_red: '赤スターター',

    // Card Names (example)
    'ヤマトタケル': 'Yamato Takeru',
  },
};